spring:
  threads:
    virtual:
      enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/inventeroy-db
    username: inventory_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

inventory:
  allow-backorer: false

management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, info"        

server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never