spring:

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

order:
  enable: true

management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, info"   

server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never