spring:
  threads:
    virtual:
      enable: true
  data:
    mongodb:
      #host: ${MONGO_HOST:localhost}
      host: mongodb
      port: 27017
      database: product-db
      username: root
      password: password
      authentication-database: admin

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true
    #hostname: localhost
    hostname: product-service


app:
  maintenance:
    message: "Sistema Operativo  - V 1.0"

management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, info"

server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: never